export const ReduxAppConstants = {

    GET_LOGGED_IN_USER_INFO: 'GET_USER_INFO',
    SET_LOGGED_IN_USER_INFO: 'SET_USER_INFO',

    LOGOUT: 'USERS_LOGOUT',

    USER_REGISTER_REQUEST: 'USER_REG_REQ',
    USER_REGISTER_RESPONSE: 'USER_REG_RES',

};